name = "Gleamveil"
author = "Marco"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "544aa76509d7586cd5088f5cf19dfd5ca1c1898d2e075266e5a00a4ea018cafb"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
