name = "Gleamveil"
author = "Bruno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f5e8670c9810011cb19c6fcf91afa791aeed4a666d62077c7380b181dfa7d73"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
