name = "Gleamveil"
author = "Marco"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03d244b9e10498e235106583c01c32302d3d1dc7ddf72c5240fd823aaa1f46ec"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
